export const GUI_READ_PARSE_QUESTIONS_FIELDS = 'GUI_READ_PARSE_QUESTIONS_FIELDS';
export const GUI_CHANGE_SELECTED_IDS         = 'GUI_CHANGE_SELECTED_IDS';
export const GUI_FIRST_SELECTED_IDS_DISPATCH = 'GUI_FIRST_SELECTED_IDS_DISPATCH';