export const GUI_READ_PARSE_QUESTIONS_FIELDS  = 'GUI_READ_PARSE_QUESTIONS_FIELDS';
export const GUI_CHANGE_SELECTED_IDS          = 'GUI_CHANGE_SELECTED_IDS';
export const GUI_FIRST_SELECTED_IDS_DISPATCH  = 'GUI_FIRST_SELECTED_IDS_DISPATCH';
export const GUI_SET_QUIZ_RADIO_OPTION        = 'GUI_SET_QUIZ_RADIO_OPTION';
export const GUI_CLEAR_QUIZ_RADIO_OPTIONS     = 'GUI_CLEAR_QUIZ_RADIO_OPTIONS';
export const GUI_REFRESH_APP                  = 'GUI_REFRESH_APP';

