export const API_CREATE_PARSED_QUESTIONS     = 'API_CREATE_PARSED_QUESTIONS';
export const API_CREATE_QUESTIONS_REQUEST    = 'API_CREATE_QUESTIONS_REQUEST';
export const API_CREATE_QUESTIONS_SUCCESS    = 'API_CREATE_QUESTIONS_SUCCESS';
export const API_CREATE_QUESTIONS_FAILURE    = 'API_CREATE_QUESTIONS_FAILURE';
export const API_CREATE_QUIZ_SUCCESS         = 'API_CREATE_QUIZ_SUCCESS';
export const API_CHANGE_SELECTED_QUESTIONS   = 'API_CHANGE_SELECTED_QUESTIONS';
export const API_GET_ALL_TEACHER_ASSIGNMENTS = 'API_GET_ALL_TEACHER_ASSIGNMENTS';
export const API_CHECK_ASSIGNMENT            = 'API_CHECK_ASSIGNMENT';
export const API_GET_ALL_QUIZZES             = 'API_GET_ALL_QUIZZES';
export const API_SAVE_ASSIGNMENT             = 'API_SAVE_ASSIGNMENT';
export const API_GET_ALL_ROLES               = 'API_GET_ALL_ROLES';
export const API_REGISTER                    = 'API_REGISTER';
export const API_LOGIN                       = 'API_LOGIN';

