export const API_CREATE_PARSED_QUESTIONS  = 'API_CREATE_PARSED_QUESTIONS';
export const API_CREATE_QUESTIONS_REQUEST = 'API_CREATE_QUESTIONS_REQUEST';
export const API_CREATE_QUESTIONS_SUCCESS = 'API_CREATE_QUESTIONS_SUCCESS';
export const API_CREATE_QUESTIONS_FAILURE = 'API_CREATE_QUESTIONS_FAILURE';